org.gradle.jvmargs=-Xmx4096M
org.gradle.parallel=true
unityStreamingAssets=.hash, .json, .xml
unityTemplateVersion=20
unityProjectPath=D:/Projects/MainWork/NovGUSpacePlanets2026
unity.projectPath=D:/Projects/MainWork/NovGUSpacePlanets2026
unity.debugSymbolLevel=none
unity.buildToolsVersion=34.0.0
unity.minSdkVersion=32
unity.targetSdkVersion=36
unity.compileSdkVersion=36
unity.applicationId=com.DefaultCompany.MixedRealityTemplate
unity.abiFilters=arm64-v8a
unity.versionCode=1
unity.versionName=2.2.0
unity.namespace=com.DefaultCompany.MixedRealityTemplate
unity.agpVersion=8.7.2
unity.androidSdkPath=C:/Program Files/Unity/Hub/Editor/6000.2.6f2/Editor/Data/PlaybackEngines/AndroidPlayer/SDK
unity.androidNdkPath=C:/Program Files/Unity/Hub/Editor/6000.2.6f2/Editor/Data/PlaybackEngines/AndroidPlayer/NDK
unity.androidNdkVersion=27.2.12479018
unity.jdkPath=C:/Program Files/Unity/Hub/Editor/6000.2.6f2/Editor/Data/PlaybackEngines/AndroidPlayer/OpenJDK
unity.javaCompatabilityVersion=VERSION_17
unity.installInBuildFolder=false
android.useAndroidX=true
android.enableJetifier=true
android.bundle.includeNativeDebugMetadata=false
org.gradle.welcome=never